added player, key handling and debug mode
grechagrecha/project_banya pull request #6
Opened 2022-10-03 23:32 UTC by grechagrecha

2022-10-03 23:50 UTC, grechagrecha commented on event_handler.py
> +from player import Player
В принципе на удаление, добавлял чисто шоб не ошибиться

2022-10-04 00:02 UTC, pskopylov requested changes

2022-10-04 00:02 UTC, pskopylov commented on player.py
> +        self.pos += self.direction * self.speed * dt
`pos` Нам то по сути и не нужен, есть же `rect.center` например. Лучше не дублировать такие данные, если надо вернуть позицию то можно написать геттер который будет `return self.rect.center`. Лучше сделать движение посредством `rect.move_ip(delta)`, а `delta` как раз будет равна `self.direction * self.speed * dt`

2022-10-04 00:02 UTC, pskopylov commented on player.py
> +        if self.direction:
Напомни плиз зачем нам тут вектор direction, ещё и нормализация. Для корректного передвижения по диагонали или как ?

2022-10-04 00:02 UTC, pskopylov commented on game.py
> +            self.player_sprite.draw(self.screen)
Вот `run` стал объемным методом. У него есть строки типа «нарисовать это и это» и «обновить это и это». Раз тут есть куски кода которые по смыслу связаны то лучше вынести их, например в `draw()`, где ты рисуешь фон и спрайт, и `update()`, где у тебя происходят апдейты спрайтов и скрина

2022-10-04 00:02 UTC, pskopylov commented on event_handler.py
> +    if keys[pygame.K_w]:
В перспективе кстати у нас будет много кнопок, так что по логике можешь wasd сразу вынести в отдельную функцию

2022-10-04 00:02 UTC, pskopylov commented on event_handler.py
> +def handle_keys(player):
Ну если тип указываешь, то и тут указать можешь

2022-10-04 00:07 UTC, grechagrecha commented on player.py
> +        if self.direction:
Да, нормализация для диагонального передвижения.

2022-10-04 13:33 UTC, pskopylov commented on game.py
> +        self.debug = None
можно `self.debug = Debug() if debug_mode else None`

2022-10-04 13:35 UTC, pskopylov commented on game.py
> +            handle_events(self.player)
довай поменьше пробелов между строк, особенно если они по одной строчке, а не осмысленными группами

2022-10-04 13:36 UTC, pskopylov submitted a review, later dismissed

2022-10-04 13:57 UTC, grechagrecha commented on game.py
> +        self.debug = None
gotovo

2022-10-04 14:00 UTC, pskopylov approved these changes

2022-10-04 14:03 UTC, merged